FROM golang:1.24-alpine

WORKDIR /app

# Install git for go mod download
RUN apk add --no-cache git

# Copy go mod files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN go build -o messaging_service .

EXPOSE 50051

CMD [ "./messaging_service" ]